
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class AMBULATORYSERVICE
{

    public int AMBULATORYID { get; set; }

    public string AMBULATORYSERVICENAME { get; set; }

    public string AMBULATORYTYPE { get; set; }

    public string AMBULATORYADD1 { get; set; }

    public string AMBULATORYADD2 { get; set; }

    public string AMBULATORYCITY { get; set; }

    public string AMBULATORYSTATE { get; set; }

    public string AMBULATORYZIP { get; set; }

    public string AMBULATORYTELEPHONE { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

    public Nullable<System.DateTime> CREATEDON { get; set; }

    public Nullable<System.DateTime> UPDATEDON { get; set; }

    public Nullable<int> USERID { get; set; }

}

}
