
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CASEMANAGERINFO
{

    public int CASEMANAGERID { get; set; }

    public string CASEMANAGERFIRSTNAME { get; set; }

    public string CASEMANAGERMIDLEINITIAL { get; set; }

    public string CASEMANAGERLASTNAME { get; set; }

    public string CASEMANAGERLISENCE { get; set; }

    public string PRACTICECITY { get; set; }

    public string PRACTICESTATE { get; set; }

    public string PRACTICEZIP { get; set; }

    public string TELEPHONE { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

}

}
