//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marlabs.Tool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportServerTempDBEntities : DbContext
    {
        public ReportServerTempDBEntities()
            : base("name=ReportServerTempDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChunkData> ChunkDatas { get; set; }
        public virtual DbSet<ChunkSegmentMapping> ChunkSegmentMappings { get; set; }
        public virtual DbSet<DBUpgradeHistory> DBUpgradeHistories { get; set; }
        public virtual DbSet<ExecutionCache> ExecutionCaches { get; set; }
        public virtual DbSet<PersistedStream> PersistedStreams { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<SegmentedChunk> SegmentedChunks { get; set; }
        public virtual DbSet<TempCatalog> TempCatalogs { get; set; }
        public virtual DbSet<TempDataSet> TempDataSets { get; set; }
        public virtual DbSet<TempDataSource> TempDataSources { get; set; }
        public virtual DbSet<SessionData> SessionDatas { get; set; }
        public virtual DbSet<SessionLock> SessionLocks { get; set; }
        public virtual DbSet<SnapshotData> SnapshotDatas { get; set; }
    }
}
