
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class DRUGCENTRE
{

    public int DRUGCENTREID { get; set; }

    public string DRUGCENTRENAME { get; set; }

    public string DRUGCENTRECONTACTNO { get; set; }

    public string DRUGCENTRECITY { get; set; }

    public string DRUGCENTRESTATE { get; set; }

    public string DRUGCENTREZIP { get; set; }

    public string DRUGCENTRELICENS { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

    public Nullable<System.DateTime> CREATEDON { get; set; }

    public Nullable<System.DateTime> UPDATEDON { get; set; }

}

}
