//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marlabs.Tool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionCache
    {
        public System.Guid ExecutionCacheID { get; set; }
        public System.Guid ReportID { get; set; }
        public int ExpirationFlags { get; set; }
        public Nullable<System.DateTime> AbsoluteExpiration { get; set; }
        public Nullable<int> RelativeExpiration { get; set; }
        public System.Guid SnapshotDataID { get; set; }
        public System.DateTime LastUsedTime { get; set; }
        public int ParamsHash { get; set; }
    }
}
