
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MEDICALINFO
{

    public int MEDICALINFOID { get; set; }

    public string BLOODGROUP { get; set; }

    public string ALLERGY { get; set; }

    public string ALLERGYINFO { get; set; }

    public string MEDICALHISTORY { get; set; }

    public string CURRENTHEALTHISSUE { get; set; }

    public Nullable<int> USERINFORMATIONID { get; set; }

    public Nullable<System.DateTime> CREATEDON { get; set; }

    public Nullable<System.DateTime> UPDATEDON { get; set; }



    public virtual USERINFORMATION USERINFORMATION { get; set; }

}

}
