

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HonkerUnionEntities : DbContext
{
    public HonkerUnionEntities()
        : base("name=HonkerUnionEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AMBULATORYSERVICE> AMBULATORYSERVICEs { get; set; }

    public virtual DbSet<MEDICALINFO> MEDICALINFOes { get; set; }

    public virtual DbSet<PROVIDERINFO> PROVIDERINFOes { get; set; }

    public virtual DbSet<USERINFORMATION> USERINFORMATIONs { get; set; }

    public virtual DbSet<USERLOGIN> USERLOGINs { get; set; }

    public virtual DbSet<CASEMANAGERINFO> CASEMANAGERINFOes { get; set; }

    public virtual DbSet<DRUGCENTRE> DRUGCENTREs { get; set; }

    public virtual DbSet<PUSHNOTIFICATION> PUSHNOTIFICATIONs { get; set; }

    public virtual DbSet<PHYSICIANINFO> PHYSICIANINFOes { get; set; }

}

}

