//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marlabs.Tool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersistedStream
    {
        public string SessionID { get; set; }
        public int Index { get; set; }
        public byte[] Content { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public string Extension { get; set; }
        public string Encoding { get; set; }
        public string Error { get; set; }
        public int RefCount { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    }
}
