
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PHYSICIANINFO
{

    public int PHYSICIANID { get; set; }

    public Nullable<int> USERID { get; set; }

    public string FIRSTNAME { get; set; }

    public string MIDLEINITIAL { get; set; }

    public string LASTNAME { get; set; }

    public string LISENCE { get; set; }

    public string ISPRIMARYPHYSICIAN { get; set; }

    public string ISSURGON { get; set; }

    public string TREATMENTTYPESPECIALIST { get; set; }

    public string PRACTICECITY { get; set; }

    public string PRACTICESTATE { get; set; }

    public string PRACTICEZIP { get; set; }

    public string TELEPHONE { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

}

}
