
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PROVIDERINFO
{

    public string PROVIDERNO { get; set; }

    public string TREATMENTTYPE { get; set; }

    public string PROVIDERNAME { get; set; }

    public string PRACTICEADD1 { get; set; }

    public string PRACTICEADD2 { get; set; }

    public string PRACTICECITY { get; set; }

    public string PRACTICESTATE { get; set; }

    public string PRACTICEZIP { get; set; }

    public string TELEPHONE { get; set; }

    public string LICENCENUMBER { get; set; }

    public string SPECIALISTTYPE { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

}

}
