
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PUSHNOTIFICATION
{

    public int NOTIFICATIONID { get; set; }

    public Nullable<int> USERID { get; set; }

    public Nullable<int> USERINFORMATIONID { get; set; }

    public string TREATMENTTYPE { get; set; }

    public string NOTIFICATIONTEXT { get; set; }

    public string PROVIDERNO { get; set; }

    public Nullable<int> PHYSICIANID { get; set; }

    public Nullable<int> AMBULATORYID { get; set; }

    public Nullable<int> CASEMANAGERID { get; set; }

    public Nullable<int> DRUGCENTREID { get; set; }

    public string PROVIDERCONFIRMSTATUS { get; set; }

    public string PHYSICIANCONFIRMSTATUS { get; set; }

    public string AMBULATORYCONFIRMSTATUS { get; set; }

    public string CASEMANAGERCONFIRMSTATUS { get; set; }

    public string DRUGCENTRECONFIRMSTATUS { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

    public Nullable<System.DateTime> CREATEDON { get; set; }

    public Nullable<System.DateTime> UPDATEDON { get; set; }

}

}
