//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marlabs.Tool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLock
    {
        public string SessionID { get; set; }
        public int LockVersion { get; set; }
    }
}
