//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marlabs.Tool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCatalog
    {
        public string EditSessionID { get; set; }
        public System.Guid TempCatalogID { get; set; }
        public string ContextPath { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Intermediate { get; set; }
        public bool IntermediateIsPermanent { get; set; }
        public string Property { get; set; }
        public string Parameter { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public byte[] DataCacheHash { get; set; }
    }
}
