
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Marlabs.Tool.Data
{

using System;
    using System.Collections.Generic;
    
public partial class USERLOGIN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USERLOGIN()
    {

        this.USERINFORMATIONs = new HashSet<USERINFORMATION>();

    }


    public int USERID { get; set; }

    public string USERNAME { get; set; }

    public string USERPASSWORD { get; set; }

    public string USERMOBILENO { get; set; }

    public string USERMAILID { get; set; }

    public string USERROLE { get; set; }

    public Nullable<System.DateTime> CREATEDON { get; set; }

    public Nullable<System.DateTime> UPDATEDON { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<USERINFORMATION> USERINFORMATIONs { get; set; }

}

}
